//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// <summary> 
/// 作者：jshailin 
/// 建立时间：2018/6/24 15:42:49 
/// 版权：2018-2036 
/// CLR版本：4.0.30319.42000 
/// 修改说明：
/// 策略模式_商场管理软件说明：本代码版权归海陵所有 
/// 唯一标识：32931afb-50dd-4ff7-baba-b59a30146f11 
/// </summary>
namespace 策略模式_商场管理软件.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
